version: "3.5"
services:
  operational_db:
    image: postgres:13.4
    network_mode: "host"
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: keykeeper,renex,registry,datasyn
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      